# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_bord',
            name='new_message',
            field=models.TextField(default='DUMMY'),
            preserve_default=False,
        ),
    ]
